#!/bin/sh

mkdir -p protos

wget -O protos/wlr-foreign-toplevel-management-unstable-v1.xml \
    https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/raw/master/unstable/wlr-foreign-toplevel-management-unstable-v1.xml

wayland-scanner client-header \
    protos/wlr-foreign-toplevel-management-unstable-v1.xml \
    wlr-foreign-toplevel-management-unstable-v1-client-protocol.h

wayland-scanner private-code protos/wlr-foreign-toplevel-management-unstable-v1.xml \
    wlr-foreign-toplevel-management-unstable-v1-protocol.c

# wayland-scanner client-header < /usr/share/wayland-protocols/staging/ext-workspace/ext-workspace-v1.xml > ext-workspace-client-protocol-v1.h
# wayland-scanner private-code < /usr/share/wayland-protocols/staging/ext-workspace/ext-workspace-v1.xml > ext-workspace-protocol-v1.c